### ISSUE TITLE
client data files missing

### ISSUE THREAD

**Issue by FreeManTR** [stevewgr/ko#24]
Hello, 
First of all thanks for your effort project looks pretty good!
Can you share client Data/Object/UI etc. Folders?

**Comment by stevewgr** [comment]
> Hello, First of all thanks for your effort project looks pretty good! Can you share client Data/Object/UI etc. Folders?

Hello @FreeManTR, it should be in Knight_c: https://mega.nz/file/FftSCDKT#zV25197wb5bZKVKn8GuuGZpYrzbRyFcbJ109RPxzuIA

I removed it from now so that the repository size is not big. It will be fetched from another repo once we start proper development.

Pull requests are welcome nevertheless.

**Comment by FreeManTR** [comment]
cool, do you have Discord maybe I can help to you in development.

**Comment by stevewgr** [comment]
> cool, do you have Discord maybe I can help to you in development.

Yes, you can join our discord at: https://discord.gg/QtnGXjGv

**Comment by mo3head** [comment]
> > Hello, First of all thanks for your effort project looks pretty good! Can you share client Data/Object/UI etc. Folders?
> 
> Hello @FreeManTR, it should be in Knight_c: https://mega.nz/file/FftSCDKT#zV25197wb5bZKVKn8GuuGZpYrzbRyFcbJ109RPxzuIA
> 
> I removed it from now so that the repository size is not big. It will be fetched from another repo once we start proper development.
> 
> Pull requests are welcome nevertheless.

Is it just me or is the requested data not inside the zip?

**Comment by stevewgr** [comment]
> > > Hello, First of all thanks for your effort project looks pretty good! Can you share client Data/Object/UI etc. Folders?
> > 
> > 
> > Hello @FreeManTR, it should be in Knight_c: https://mega.nz/file/FftSCDKT#zV25197wb5bZKVKn8GuuGZpYrzbRyFcbJ109RPxzuIA
> > I removed it from now so that the repository size is not big. It will be fetched from another repo once we start proper development.
> > Pull requests are welcome nevertheless.
> 
> Is it just me or is the requested data not inside the zip?

Hello @mo3head, it's under the WarFare directory inside the Knight_c.zip archive. However I don't think it's the complete game assets, since it was WIP irc.
This project will target version 1097 and the game assets will be maintained in this repo: https://github.com/stevewgr/ko-assets

I'll update once I made the client & server match with this version unless you want to try too in the meantime.

**Comment by stevewgr** [comment]
I'm closing this ticket, since the answer is here: https://github.com/stevewgr/ko/issues/24#issuecomment-1200125621

The game should now be runnable. We have the game and server assets synced, as well as database.

Feel free to open a different ticket if there are anymore questions.
